In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("Zomato-data-.csv")
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [4]:
df.describe()

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [5]:
df.head(5)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [6]:
df["name"] = df["name"].str.upper()

In [7]:
df.head(4)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,JALSA,Yes,Yes,4.1/5,775,800,Buffet
1,SPICE ELEPHANT,Yes,No,4.1/5,787,800,Buffet
2,SAN CHURRO CAFE,Yes,No,3.8/5,918,800,Buffet
3,ADDHURI UDUPI BHOJANA,No,No,3.7/5,88,300,Buffet

In [8]:
df["name"].isnull().sum()

np.int64(0)

In [10]:
df["online_order"].isnull().sum()

np.int64(0)

In [11]:
df["book_table"].unique()

array(['Yes', 'No'], dtype=object)

In [12]:
df["book_table"].isnull().sum()

np.int64(0)

In [13]:
df["rate"].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', '2.9/5', '3.5/5', '2.6/5', '3.8 /5', '3.4/5'],
      dtype=object)

In [15]:
df["rate"].dtype

dtype('O')

In [19]:
df["rate"] = df["rate"].str.replace("/5"," ")

In [20]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,JALSA,Yes,Yes,4.1,775,800,Buffet
1,SPICE ELEPHANT,Yes,No,4.1,787,800,Buffet
2,SAN CHURRO CAFE,Yes,No,3.8,918,800,Buffet
3,ADDHURI UDUPI BHOJANA,No,No,3.7,88,300,Buffet
4,GRAND VILLAGE,No,No,3.8,166,600,Buffet

In [22]:
df["rate"]= df["rate"].astype(float)

In [23]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,JALSA,Yes,Yes,4.1,775,800,Buffet
1,SPICE ELEPHANT,Yes,No,4.1,787,800,Buffet
2,SAN CHURRO CAFE,Yes,No,3.8,918,800,Buffet
3,ADDHURI UDUPI BHOJANA,No,No,3.7,88,300,Buffet
4,GRAND VILLAGE,No,No,3.8,166,600,Buffet
...,...,...,...,...,...,...,...
143,MELTING MELODIES,No,No,3.3,0,100,Dining
144,NEW INDRAPRASTA,No,No,3.3,0,150,Dining
145,ANNA KUTEERA,Yes,No,4.0,771,450,Dining
146,DARBAR,No,No,3.0,98,800,Dining
147,VIJAYALAKSHMI,Yes,No,3.9,47,200,Dining

In [26]:
df["votes"] = df["votes"].fillna(0)

In [27]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,JALSA,Yes,Yes,4.1,775,800,Buffet
1,SPICE ELEPHANT,Yes,No,4.1,787,800,Buffet
2,SAN CHURRO CAFE,Yes,No,3.8,918,800,Buffet
3,ADDHURI UDUPI BHOJANA,No,No,3.7,88,300,Buffet
4,GRAND VILLAGE,No,No,3.8,166,600,Buffet
...,...,...,...,...,...,...,...
143,MELTING MELODIES,No,No,3.3,0,100,Dining
144,NEW INDRAPRASTA,No,No,3.3,0,150,Dining
145,ANNA KUTEERA,Yes,No,4.0,771,450,Dining
146,DARBAR,No,No,3.0,98,800,Dining
147,VIJAYALAKSHMI,Yes,No,3.9,47,200,Dining

In [28]:
df["approx_cost(for two people)"].isnull().sum()

np.int64(0)

In [29]:
df["approx_cost(for two people)"].unique()

array([800, 300, 600, 700, 550, 500, 450, 650, 400, 900, 200, 750, 150,
       850, 100, 350, 250, 950])

In [30]:
df["listed_in(type)"].unique()

array(['Buffet', 'Cafes', 'other', 'Dining'], dtype=object)

In [31]:
df["listed_in(type)"].value_counts()

listed_in(type)
Dining    110
Cafes      23
other       8
Buffet      7
Name: count, dtype: int64

In [32]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,JALSA,Yes,Yes,4.1,775,800,Buffet
1,SPICE ELEPHANT,Yes,No,4.1,787,800,Buffet
2,SAN CHURRO CAFE,Yes,No,3.8,918,800,Buffet
3,ADDHURI UDUPI BHOJANA,No,No,3.7,88,300,Buffet
4,GRAND VILLAGE,No,No,3.8,166,600,Buffet
...,...,...,...,...,...,...,...
143,MELTING MELODIES,No,No,3.3,0,100,Dining
144,NEW INDRAPRASTA,No,No,3.3,0,150,Dining
145,ANNA KUTEERA,Yes,No,4.0,771,450,Dining
146,DARBAR,No,No,3.0,98,800,Dining
147,VIJAYALAKSHMI,Yes,No,3.9,47,200,Dining

In [39]:
df.to_csv(r"C:\Users\EKANKSH\OneDrive\Documents\zomato_cleaned.csv",index = False)